### ISSUE TITLE
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by beaufour** [briancurt/pixelarity-download#8]
I get this error when running the docker container:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
```

**Comment by beaufour** [comment]
Obviously ugly, but this worked around it:

```
modified   src/pixelarity-download.py
@@ -82,7 +82,7 @@ def get_templates():
     templates = []
 
     browser = RoboBrowser(parser='html.parser')
-    browser.open("https://pixelarity.com/")
+    browser.open("https://pixelarity.com/", verify=False)
     r = browser.parsed()
     soup = BeautifulSoup(str(r[0]), features="html.parser")
     t = soup.find("section").find_all("article")
@@ -126,7 +126,7 @@ def main():
     browser = RoboBrowser(parser='html.parser')
     templates = get_templates()
 
-    browser.open("https://pixelarity.com/login")
+    browser.open("https://pixelarity.com/login", verify=False)
 ```

**Comment by briancurt** [comment]
@beaufour There is a server-side problem with the certificate chain. I agree this is an ugly workaround but it's tolerable in this case. Thanks!
